Repository fixmyrights/discord-bot, pull requests merged in 2020-02, with the labels that each got.

#20 Feature/split commands
  data/config.json
  package-lock.json
  package.json
  src/api.js
  src/command_handlers/command_handler.js
  src/command_handlers/help.js
  src/command_handlers/ping.js
  src/command_handlers/scan.js
  src/index.js
  src/services/legiscan.js
Labels: feature

#18 Following Node.js documentation's best practices for writing to a file
  src/database.js
Labels: feature

#23 Database stores config and cron works.
  data/default-config.json
  src/commands/config/cron.js
  src/commands/config/handler.js
  src/commands/scan.js
  src/database.js
  src/index.js
  src/services/legiscan.js
Labels: feature

#29 Setting up Jest.
  .circleci/config.yml
  .eslintignore
  .eslintrc.js
  .prettierignore
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/logger.spec.js
  tests/dummy.feature.js
  tests/jest.config.js
  tests/setup.js
Labels: feature

#36 Setting up Nodemon.
  README.md
  nodemon.json
  package-lock.json
  package.json
Labels: Feature

#41 Implement dotenv.
  .env.template
  .gitignore
  .prettierignore
  README.md
  data/credentials.json.template
  docker-compose.yml
  package-lock.json
  package.json
  src/commands/bill/scan.js
  src/index.js
  src/services/legiscan.js
Labels: Feature

#51 Fix: Adding robustness to the bill and config handler's
  src/commands/bill/handler.js
  src/commands/config/handler.js
Labels: Bug
